name: CI

on:
  push:
    branches:
      - thepit_v2
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all
